#!/usr/bin/env bash
# Vendor the core entropy development from a local checkout of teorth/pfr.
#
# Usage: scripts/vendor.sh /path/to/pfr-checkout
#
# Computes the transitive import closure (within the PFR package) of the entry
# modules below, copies each file into InfoTheory/PFR/ preserving its path,
# rewrites `import PFR.*` -> `import InfoTheory.PFR.*`, prepends a provenance
# header, and regenerates the manifest section of VENDORED.md.
#
# Compatible with macOS bash 3.2; uses perl for in-place edits (portable).
set -euo pipefail

SRC="${1:?usage: scripts/vendor.sh /path/to/pfr-checkout}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/InfoTheory/PFR"
COMMIT="$(git -C "$SRC" rev-parse HEAD)"
DATE="$(git -C "$SRC" show -s --format=%cs HEAD)"

ENTRY_MODULES="
PFR.ForMathlib.Entropy.Basic
PFR.ForMathlib.Entropy.Measure
PFR.ForMathlib.Entropy.Kernel.Basic
PFR.ForMathlib.Entropy.Kernel.MutualInfo
"

mod_to_path() { echo "${1//.//}.lean"; }

# --- BFS over `import PFR.*` lines to compute the closure -------------------
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
seen="$tmpdir/seen" queue="$tmpdir/queue"
echo "$ENTRY_MODULES" | grep -v '^$' > "$queue"
: > "$seen"

while [ -s "$queue" ]; do
  mod="$(head -n1 "$queue")"
  tail -n +2 "$queue" > "$queue.tmp" && mv "$queue.tmp" "$queue"
  grep -qx "$mod" "$seen" && continue
  echo "$mod" >> "$seen"
  file="$SRC/$(mod_to_path "$mod")"
  [ -f "$file" ] || { echo "error: $file not found (module $mod)" >&2; exit 1; }
  grep -E '^(public |private |meta )?import (all )?PFR\.' "$file" \
    | perl -pe 's/^(?:public |private |meta )?import (?:all )?//; s/[ \t].*//' \
    >> "$queue" || true
done

sort "$seen" > "$tmpdir/closure"
n="$(wc -l < "$tmpdir/closure" | tr -d ' ')"
echo "closure: $n modules"

# --- Copy, rewrite imports, prepend provenance headers ----------------------
rm -rf "$DEST"
while read -r mod; do
  rel="$(mod_to_path "$mod")"                 # PFR/ForMathlib/....lean
  out="$ROOT/InfoTheory/$rel"                 # InfoTheory/PFR/ForMathlib/....lean
  mkdir -p "$(dirname "$out")"
  {
    echo "-- VENDORED from teorth/pfr @ $COMMIT"
    echo "-- Upstream path: $rel"
    echo "-- Do not edit by hand; see VENDORED.md. Re-sync with scripts/vendor.sh."
    cat "$SRC/$rel"
  } > "$out"
  perl -pi -e 's/^((?:public |private |meta )?import (?:all )?)PFR\./${1}InfoTheory.PFR./' "$out"
  echo "  vendored $rel"
done < "$tmpdir/closure"

# --- Regenerate manifest section of VENDORED.md ------------------------------
manifest="$tmpdir/manifest"
{
  echo "<!-- BEGIN VENDOR MANIFEST (generated by scripts/vendor.sh; do not edit) -->"
  echo "Upstream: https://github.com/teorth/pfr @ \`$COMMIT\` ($DATE)"
  echo ""
  echo "Modules ($n):"
  echo ""
  while read -r mod; do echo "- \`$mod\`"; done < "$tmpdir/closure"
  echo "<!-- END VENDOR MANIFEST -->"
} > "$manifest"

if [ -f "$ROOT/VENDORED.md" ] && grep -q 'BEGIN VENDOR MANIFEST' "$ROOT/VENDORED.md"; then
  MANIFEST="$manifest" perl -0pi -e '
    open(my $fh, "<", $ENV{MANIFEST}) or die "cannot read manifest: $!";
    local $/; my $m = <$fh>; chomp $m;
    s/<!-- BEGIN VENDOR MANIFEST.*END VENDOR MANIFEST -->/$m/s;
  ' "$ROOT/VENDORED.md"
  echo "VENDORED.md manifest updated"
else
  echo "note: VENDORED.md manifest markers not found; manifest written to stdout" >&2
  cat "$manifest"
fi

echo "done. Remember: update lean-toolchain and the Mathlib rev in lakefile.toml"
echo "to match the PFR checkout when re-syncing, then 'lake update mathlib &&"
echo "lake exe cache get && lake build'."
